import Head from "next/head";
import { NextPageCustomized } from "utils/interfaces";
import SectionTooltip from "sections/tooltip";

const PageTooltip: NextPageCustomized = () => {
  return <SectionTooltip />;
};

PageTooltip.getHead = () => {
  return (
    <Head>
      <title>More/Tooltip - Zoom</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageTooltip;
