import Head from "next/head";
import { NextPageCustomized } from "utils/interfaces";
import SectionTable from "sections/table";

const PageComponentTable: NextPageCustomized = () => {
  return <SectionTable />;
};

PageComponentTable.getHead = () => {
  return (
    <Head>
      <title>Component Table - Zoom</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageComponentTable;
