import Head from "next/head";
import "assets/styles/globals.css";
import LayoutDefault from "layouts";
import { AppPropsCustomized } from "utils/interfaces";

function MyApp({ Component, pageProps }: AppPropsCustomized) {
  // Use the layout defined at the page level, or else use default layout
  const getLayout =
    Component.getLayout ?? ((page) => <LayoutDefault>{page}</LayoutDefault>);

  // Use the head defined at the page level, or else use default head
  const getHead =
    Component.getHead ??
    (() => (
      <Head>
        <title>Zoom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    ));

  return (
    <>
      {getHead()}
      {getLayout(<Component {...pageProps} />)}
    </>
  );
}

export default MyApp;
