import Head from "next/head";
import { NextPageCustomized } from "utils/interfaces";

const PageTimeline: NextPageCustomized = () => {
  return <>Timeline</>;
};

PageTimeline.getHead = () => {
  return (
    <Head>
      <title>More/Timeline - Zoom</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageTimeline;
