import Head from "next/head";
import { ReactNode, ReactElement } from "react";

interface IProps {
  children: ReactNode | string;
  head?: ReactElement;
}

const LayoutDefault = ({ children, head }: IProps) => {
  // Use the head defined at the page level, or else use default head
  return (
    <>
      {head ?? (
        <Head>
          <title>Zoom</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      )}
      <header />
      <main>{children}</main>
      <footer />
    </>
  );
};

export default LayoutDefault;
