name: Share data between jobs
on: [push]
jobs:
  job_1:
    name: Add 4 and 6
    runs-on: ubuntu-20.04
    steps:
      - name: Calculate 4 plus 6
        shell: bash
        run: |
          expr 4 + 6 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_2:
    name: Multiply by 3
    needs: job_1
    runs-on: windows-2022
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Calculate result with 3
        shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 3 > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_3:
    name: Display result
    needs: job_2
    runs-on: macos-11
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
