import Head from "next/head";
import { NextPageCustomized } from "utils/interfaces";
import SectionAccordion from "sections/accordion";

const PageAccordion: NextPageCustomized = () => {
  return <SectionAccordion />;
};

PageAccordion.getHead = () => {
  return (
    <Head>
      <title>Menus/Accordion - Zoom</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageAccordion;
