import Head from "next/head";
import { NextPageCustomized } from "utils/interfaces";

const PageTabs: NextPageCustomized = () => {
  return <>PageTabs</>;
};

PageTabs.getHead = () => {
  return (
    <Head>
      <title>Menus/Tabs - Zoom</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageTabs;
